# Generated by Django 3.0.3 on 2020-03-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_active_status',
            field=models.BooleanField(default=True),
        ),
    ]
