# Generated by Django 3.0.3 on 2020-03-07 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_company_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subscription_expiry',
            field=models.DateField(default=datetime.date(2020, 3, 14)),
        ),
    ]
