# Generated by Django 3.0.2 on 2020-02-20 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='office_end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office_start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='internationalization',
            field=models.CharField(default='EN', max_length=2),
        ),
    ]
