# Generated by Django 3.0.2 on 2020-02-18 17:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agenda', models.TextField()),
                ('duration', models.DurationField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('meeting_status', models.CharField(choices=[('DR', 'Draft'), ('IN', 'Initiated'), ('CO', 'Completed'), ('FI', 'Finalized'), ('PO', 'Postponed'), ('CA', 'Canceled')], default='DR', max_length=2)),
                ('type', models.CharField(choices=[('PV', 'Private'), ('PU', 'Public'), ('CF', 'Conference')], default='PU', max_length=2)),
                ('participant_email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'start_date',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_status', models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('DE', 'Declined'), ('PO', 'Postponed')], default='PE', max_length=2)),
                ('participant_message', models.TextField(blank=True, null=True)),
                ('meeting_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_to_participant', to='meeting.Host')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_to_meeting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='participant',
            field=models.ManyToManyField(related_name='participant', through='meeting.Status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meeting.Host')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Room')),
            ],
        ),
    ]
