# Generated by Django 3.0.3 on 2020-03-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='meeting_status',
            field=models.CharField(choices=[('DR', 'Draft'), ('IN', 'Initiated'), ('CO', 'Completed'), ('FI', 'Finalized'), ('ON', 'Ongoing'), ('CA', 'Canceled')], default='DR', max_length=2),
        ),
    ]
