# Generated by Django 3.0.2 on 2020-02-29 08:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('no_of_floors', models.CharField(max_length=25)),
                ('shared_company_floors', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_available', models.CharField(choices=[('A', 'Available'), ('UC', 'Under Construction'), ('UR', 'Under Renovation'), ('SD', 'Shut Down')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('room_amenity', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('room_type', models.CharField(choices=[('CR', 'Confrence Room'), ('MR', 'Meeting Room'), ('PO', 'Private Office'), ('DH', 'Discussion Hall'), ('BR', 'Break Room')], max_length=2)),
                ('room_description', models.TextField(blank=True, null=True)),
                ('room_capacity', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='property.Property')),
            ],
        ),
    ]
