# Generated by Django 3.0.2 on 2020-02-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
