# Generated by Django 3.0.2 on 2020-02-26 20:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='no_of_floors',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='shared_company_floors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
