# Generated by Django 3.0.2 on 2020-02-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200229_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
