# Generated by Django 3.0.3 on 2020-03-05 18:03

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20200305_2257'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0003_auto_20200229_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_start_time', models.DateTimeField()),
                ('booking_end_time', models.DateTimeField()),
                ('other_participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.Host')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Room')),
            ],
        ),
    ]
